"""gendigits.py: emit patches/digits.inc, ten 16x16 digit graphics (each = tiles TL, TR, BL, BR, 32 bytes apiece) for the cheats screen.
Chunky 5x7 digits drawn at 2x scale with a 1 px shadow (OBJ palette index 13 shadow, 14 face, the same two indices the game font uses)."""
import os

FONT = {
    "0": ["01110", "10001", "10011", "10101", "11001", "10001", "01110"],
    "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
    "2": ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
    "3": ["11110", "00001", "00001", "01110", "00001", "00001", "11110"],
    "4": ["00010", "00110", "01010", "10010", "11111", "00010", "00010"],
    "5": ["11111", "10000", "11110", "00001", "00001", "10001", "01110"],
    "6": ["00110", "01000", "10000", "11110", "10001", "10001", "01110"],
    "7": ["11111", "00001", "00010", "00100", "01000", "01000", "01000"],
    "8": ["01110", "10001", "10001", "01110", "10001", "10001", "01110"],
    "9": ["01110", "10001", "10001", "01111", "00001", "00010", "01100"],
}


def face(d, x, y):
    gx, gy = x - 3, y - 1
    if 0 <= gx < 10 and 0 <= gy < 14:
        return FONT[d][gy // 2][gx // 2] == "1"
    return False


def px(d, x, y):
    if face(d, x, y):
        return 14
    if face(d, x - 1, y - 1):
        return 13
    return 0


def tile(d, tx, ty):
    bp = [[0] * 8 for _ in range(4)]
    for r in range(8):
        for c in range(8):
            v = px(d, tx * 8 + c, ty * 8 + r)
            for p in range(4):
                if v >> p & 1:
                    bp[p][r] |= 0x80 >> c
    out = []
    for r in range(8):
        out += [bp[0][r], bp[1][r]]
    for r in range(8):
        out += [bp[2][r], bp[3][r]]
    return out


data = []
for d in "0123456789":
    for (tx, ty) in ((0, 0), (1, 0), (0, 1), (1, 1)):
        data += tile(d, tx, ty)
lines = ["digit_gfx:                      ; 10 digits x 128 bytes (generated by gendigits.py)"]
for i in range(0, len(data), 16):
    lines.append("    db " + ",".join("$%02X" % b for b in data[i:i + 16]))
here = os.path.dirname(os.path.abspath(__file__))
open(os.path.join(here, "patches", "digits.inc"), "w").write("\n".join(lines) + "\n")
print(len(data), "bytes")
