"""genlevelnames.py <levelnames.txt>: turn the output of run_levelnames.sh (one 'wN lM  GET READY FOR | NAME' line per level) into
patches/levelnames.inc (asar): a pointer table in (world, level) order and the strings, each as x-origin byte + zero-terminated text,
where x centres the text on the 256 px screen at 12 px per glyph. Also writes LEVEL_SELECT.md, the world/level -> name list."""
import os
import re
import sys

COUNTS = [25, 14, 19, 4, 3]
WORLDS = ["HORROR", "ADVENTURE", "FANTASY", "TIMED", "ENDING"]
names = {}
for line in open(sys.argv[1]).read().splitlines():
    m = re.match(r"w(\d+) l(\d+)\s+(.*)", line)
    if not m:
        continue
    w, l, text = int(m[1]), int(m[2]), m[3]
    parts = [p.strip() for p in text.split("|")]
    if parts and parts[0].startswith("GET READY"):
        parts = parts[1:]
    names[(w, l)] = " ".join(p for p in parts if p) or "?"

# two bonus rooms show a "COLLECT THIRTY FIVE ..." card instead of GET READY: use their name-table names
names[(0, 23)] = "KEY HUNT"
names[(3, 2)] = "TIMED ZONE C"

here = os.path.dirname(os.path.abspath(__file__))
out = []
ptrs = []
strings = []
md = ["# Pagemaster - CHEATS level select: world / level -> level name", "",
      "The CHEATS screen lists levels by the game's own index (1-based here). Names read back from the in-game GET READY card.", ""]
idx = 0
for w, cnt in enumerate(COUNTS):
    md.append("## World %d - %s (%d levels)" % (w + 1, WORLDS[w], cnt))
    md.append("")
    for l in range(cnt):
        name = names.get((w, l), "?")
        safe = re.sub(r"[^A-Z ]", "", name.upper())
        x = max(0, 128 - 6 * len(safe))
        label = "nm%d" % idx
        ptrs.append(label)
        strings.append("%s:\n    db %d, \"%s\", 0" % (label, x, safe))
        md.append("%2d. %s" % (l + 1, name))
        idx += 1
    md.append("")
out.append("; generated by genlevelnames.py from the GET READY cards of all 65 levels")
out.append("name_ptrs:")
out.append("    dw " + ", ".join(ptrs))
out += strings
open(os.path.join(here, "patches", "levelnames.inc"), "w", newline="\n").write("\n".join(out) + "\n")
open(os.path.join(here, "LEVEL_SELECT.md"), "w", newline="\n").write("\n".join(md) + "\n")
print(idx, "levels, longest", max(len(n) for n in names.values()))
