"""genthud.py: synthesise a stamp thud, BRR-encode it, and emit patches/thud.inc (asar) for the title sound bank.

What it builds (formats reverse engineered from the SPC driver, see NOTES.md "Sound on the title"):
  * a sample block   [len16] fd  size16 loopoff16 H  header[H] BRR[size]      -> becomes sample index 13 ($0D) of bank 1
  * a group block    [len16] fe  literal-run stream (n-1, bytes...) ff 00       -> replaces the 4th dummy effect group (ids $70-$7F)
    group data = word 16 (count), 16 effect offsets, then the effect programs; effect 0 (id $70) is the thud, the others stay f4 ff
  * a copy of bank 1's block list with those two changes (the original list has no room to grow)
Also writes shots/thud_preview.wav (the raw sample at 32 kHz) so it can be listened to.
"""
import math
import os
import random
import struct
import wave

RATE = 32000
DUR = 0.30
N = int(RATE * DUR) // 16 * 16

# ---- synth ----
rnd = random.Random(7)
pcm = []
phase = 0.0
for n in range(N):
    t = n / RATE
    f = 46.0 + 120.0 * math.exp(-t / 0.022)
    phase += 2 * math.pi * f / RATE
    env = (1 - math.exp(-t / 0.0012)) * math.exp(-t / 0.075)
    body = math.sin(phase) * env
    click = (rnd.random() * 2 - 1) * math.exp(-t / 0.005) * 0.30
    pcm.append(body * 0.95 + click)
fade = 240
for i in range(fade):
    pcm[N - 1 - i] *= i / fade
peak = max(abs(x) for x in pcm)
pcm = [int(round(x / peak * 14000)) for x in pcm]

# ---- BRR (filter 0 only) ----
brr = bytearray()
for b in range(N // 16):
    blk = pcm[b * 16:(b + 1) * 16]
    m = max(abs(x) for x in blk)
    rng = 0
    while rng < 12 and m / (2 ** (rng - 1) if rng else 0.5) > 7.5:
        rng += 1
    step = 2 ** (rng - 1) if rng else 0.5
    nib = [max(-8, min(7, int(round(x / step)))) for x in blk]
    end = 1 if b == N // 16 - 1 else 0
    brr.append((rng << 4) | (0 << 2) | (0 << 1) | end)
    for i in range(0, 16, 2):
        brr.append(((nib[i] & 15) << 4) | (nib[i + 1] & 15))

# ---- sample block ----
HDR = bytes([0x50, 0x50, 0x8F, 0xE0, 0x00])        # vol L, vol R, ADSR1 (enable, AR 15), ADSR2 (SL 7, SR 0: hold), tuning
payload = bytes([0xFD]) + struct.pack("<HH", len(brr), len(brr)) + bytes([len(HDR)]) + HDR + bytes(brr)
sample_block = struct.pack("<H", len(payload)) + payload

# ---- effect group ----
PRE = bytes.fromhex("f4 fa f6 ef 60 ee 0c f0 00 ec 60 eb 0c ed 00 e9 00")
NOTE = 76                                            # pitch table index 76 = $1000 = native 32 kHz
PROG = PRE + bytes([0xFE, 0x0D, NOTE, 0x7F, 0xFF])   # instrument = sample 13, the note, duration, end
progs = [PROG] + [bytes([0xF4, 0xFF])] * 15
table = 0x22
offs, o = [], table
for p in progs:
    offs.append(o)
    o += len(p)
group = struct.pack("<H", 16) + b"".join(struct.pack("<H", x) for x in offs) + b"".join(progs)
stream = bytearray([0xFE])
for i in range(0, len(group), 128):
    chunk = group[i:i + 128]
    stream.append(len(chunk) - 1)
    stream += chunk
stream += bytes([0xFF, 0x00])
group_block = struct.pack("<H", len(stream)) + bytes(stream)

# ---- asar include ----
def db(label, data):
    lines = [label + ":"]
    for i in range(0, len(data), 16):
        lines.append("    db " + ",".join("$%02X" % b for b in data[i:i + 16]))
    return "\n".join(lines)


here = os.path.dirname(os.path.abspath(__file__))
inc = ["; generated by genthud.py", db("thud_group_block", group_block), db("thud_sample_block", sample_block)]
open(os.path.join(here, "patches", "thud.inc"), "w", newline="\n").write("\n".join(inc) + "\n")

with wave.open(os.path.join(here, "shots", "thud_preview.wav"), "wb") as w:
    w.setnchannels(1)
    w.setsampwidth(2)
    w.setframerate(RATE)
    w.writeframes(b"".join(struct.pack("<h", x) for x in pcm))
print("pcm", N, "samples;", len(brr), "BRR bytes; sample block", len(sample_block), "; group block", len(group_block), "; effect offsets", [hex(x) for x in offs[:3]])
